//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：ApplyOrderEntity 
    /// </summary>
    [Serializable()]
    public partial class ApplyOrderEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ApplyOrderId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ApplyOrderNo { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AddressInfo { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberMobile { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? ServiceDate { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ServiceTime { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? PayMoney { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? TotalMoney { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherId { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SubjectId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SubjectName { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? CashType { get; set; }

           
    }    
}
	