//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：AuditOrganizationEntity 
    /// </summary>
    [Serializable()]
    public partial class AuditOrganizationEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string OrganizationId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Name { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AddressInfo { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? IsTake { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? Lng { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? Lat { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ConectName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ConectTel { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string Content { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string FaceImage { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? MakeMoney { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string VideoContent { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string PriceContent { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? SortNum { get; set; }

           
    }    
}
	