//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：AuditOrderEntity 
    /// </summary>
    [Serializable()]
    public partial class AuditOrderEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AuditOrderId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AuditOrderNo { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CarNum { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Mobile { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? ServiceDate { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ServiceTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string OrganizationId { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? Price { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string OrganizationName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CarFrameNum { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? RegisterTime { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? CashType { get; set; }

           
    }    
}
	