//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：ExamPlaceMasterEntity 
    /// </summary>
    [Serializable()]
    public partial class ExamPlaceMasterEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ExamPlaceMasterId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MasterAccount { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MasterName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MasterPwd { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MasterTel { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string FaceImage { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ExamPlaceIds { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ExamPlaceNames { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Remark { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

           
    }    
}
	