//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：MemberEntity 
    /// </summary>
    [Serializable()]
    public partial class MemberEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Mobile { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CarNumber { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolId { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? Point { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LevName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LevId { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Pwd { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string OpenId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string HeadIcon { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string NikeName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherName { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Type { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AddressInfo { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? IsOwner { get; set; }

                    
		/// <summary>
		/// datetime:报名缴费自动成为高级VIP客户，VIP有效期时间为一年
		/// </summary>	
                 
		public DateTime? VipOverDate { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? StudyHour1 { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? StudyHour2 { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SimpleSpelling { get; set; }

           
    }    
}
	