//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：RuleEntity 
    /// </summary>
    [Serializable()]
    public partial class RuleEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string RuleId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Name { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberLevName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberLevId { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? RuleOperation { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Type { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? CosMoney { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? GivePoint { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? LimitingValue { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

           
    }    
}
	