//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：StudyOrderEntity 
    /// </summary>
    [Serializable()]
    public partial class StudyOrderEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string StudyOrderId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string StudyOrderNo { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? StudyType { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberMobile { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberId { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? ServiceDate { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ServiceTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherId { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

           
    }    
}
	