//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：SubjectEntity 
    /// </summary>
    [Serializable()]
    public partial class SubjectEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SubjectId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SubjectName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ItemId { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? MakeMoney { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? Price { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Remark { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

           
    }    
}
	