//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：TeacherEntity 
    /// </summary>
    [Serializable()]
    public partial class TeacherEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SchoolId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Name { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Mobile { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LevId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string LevName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string FaceImage { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CreateTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CreateId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Pwd { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? IsWithDriving { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ProvinceName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CityName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CountyName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AddressInfo { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? IsTakeCar { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string Content { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string OpenId { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string ServicesAreaIds { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string ServicesAreaNames { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? WithDrivingPrice_SW { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? WithDrivingPrice_XW { get; set; }

                    
		/// <summary>
		/// decimal:
		/// </summary>	
                 
		public decimal? WithDrivingPrice_WS { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TakeCarType { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string IdCard { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? SortNum { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MasterAccount { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string CarNumber { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string SimpleSpelling { get; set; }

           
    }    
}
	