//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：TradeLogEntity 
    /// </summary>
    [Serializable()]
    public partial class TradeLogEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TradeLogId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string AccountId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string UserName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string ObjectId { get; set; }

                    
		/// <summary>
		/// numeric:
		/// </summary>	
                 
		public decimal? Money { get; set; }

                    
		/// <summary>
		/// tinyint:
		/// </summary>	
                 
		public byte? Operate { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? AddTime { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Remark { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? Status { get; set; }

           
    }    
}
	