//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-18 15:21:41 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace QX360.Model
{
    /// <summary>
    /// 数据表实体类：WithDringCommitteeEntity 
    /// </summary>
    [Serializable()]
    public partial class WithDringCommitteeEntity:BaseModel
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string WithDringCommitteeId { get; set; }

                    
		/// <summary>
		/// int:
		/// </summary>	
                 
		public int? CommitLev { get; set; }

                    
		/// <summary>
		/// datetime:
		/// </summary>	
                 
		public DateTime? CommitTime { get; set; }

                    
		/// <summary>
		/// text:
		/// </summary>	
                 
		public string CommitContent { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string TeacherName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string WithDringOrderId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberId { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberName { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string MemberMobile { get; set; }

           
    }    
}
	